### ISSUE TITLE
No Calendar Events

### ISSUE THREAD

**Issue by sc-steven** [LJPc-solutions/freescout-calendar-module#30]
It appears this module is designed to only use external calendars (not able to create a shareable calendar from within this module?)

When i create a Calendar in Google GMail and set it to shareable publicly, i then copy either the share link (no title created) or the ICS link, none of the vents from the calendar show up in the module calendar view. I am unsure how to troubleshoot this as there are no calendar logs present.

Also when i remove a link from the Module settings the shareable calendar links created by this module always remain. Is there a way to delete these?

<img width="412" alt="calendar-list" src="https://github.com/LJPc-solutions/freescout-calendar-module/assets/54784064/073f4d0a-4f4c-44a6-9f87-06d0e8b23ca8">

<img width="856" alt="calendar-settings" src="https://github.com/LJPc-solutions/freescout-calendar-module/assets/54784064/2abf47c0-f961-4c76-a25c-e82876fe5f84">

**Comment by Lars-** [comment]
The module is not designed for external calendars only. Just typ in a name instead of an ics link and you'll have a local calendar.

But it should (and does) work when you add an ics to the list. I use it myself every day. 

And removing the link should also remove the calendar. 

Unfortunately I don't have any time at the moment to debug these issues. Feel free to do it yourself (by changing code) and send in a pull request when it's fixed.

I'm sorry for the inconvenience.
